package com.allegaeon.catworld.service;
import com.allegaeon.catworld.dto.*; import com.allegaeon.catworld.exception.*; import com.allegaeon.catworld.model.*; import com.allegaeon.catworld.repository.TransferRateRepository; import com.allegaeon.catworld.security.CurrentUserAccountService; import com.allegaeon.catworld.validation.WholeMonetaryAmount; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal;
@Service @RequiredArgsConstructor public class TransferRateService {
 private final TransferRateRepository repository; private final CurrentUserAccountService users; private final NightlyReferenceRateAuthorizationPolicy policy;
 @Transactional(readOnly=true) public TransferRateResponseDTO get(){ policy.authorizeRead(users.getCurrentUserAccount()); return response(repository.findById(1L).orElse(null)); }
 @Transactional public TransferRateResponseDTO configure(BigDecimal value){ policy.authorizeMutation(users.getCurrentUserAccount()); if(value==null||value.signum()<=0||!WholeMonetaryAmount.isSupported(value)) throw new BadRequestException("Transfer rate must be a positive whole number with at most 19 digits"); TransferRate rate=repository.findCurrentForUpdate().orElseGet(()->TransferRate.builder().id(1L).build()); BigDecimal canonical=WholeMonetaryAmount.canonicalize(value); if(rate.getTransferRate()==null||rate.getTransferRate().compareTo(canonical)!=0){rate.setTransferRate(canonical); repository.saveAndFlush(rate);} return response(rate); }
 @Transactional public void clear(){ policy.authorizeMutation(users.getCurrentUserAccount()); repository.findCurrentForUpdate().ifPresent(rate->{if(rate.getTransferRate()!=null){rate.setTransferRate(null);repository.saveAndFlush(rate);}}); }
 private TransferRateResponseDTO response(TransferRate rate){return TransferRateResponseDTO.builder().transferRate(rate==null?null:rate.getTransferRate()).build();}
}
