spring.application.name=catworld
catworld.security.username=${CATWORLD_SECURITY_USERNAME}
catworld.security.password=${CATWORLD_SECURITY_PASSWORD}
catworld.security.cors-allowed-origins=${CATWORLD_SECURITY_CORS_ALLOWED_ORIGINS:http://localhost:4200}