spring.datasource.url=jdbc:mysql://localhost:3306/catworld?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=catworld
spring.datasource.password=catworld

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true